version: "3.7"

services:

  # mongo:
  #   image: mongo:4.2
  #   hostname: mongo
  #   container_name: mongo
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_DATABASE: miniautorizador
  #     MONGO_INITDB_ROOT_USERNAME: user
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   volumes:
  #     - ./scripts/init.js:/docker-entrypoint-initdb.d/init.js:ro

  postgres:
    container_name: postgres-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "retrocards"
      TZ: "America/Sao_Paulo"
    restart: always